Feature creature reading
adamK50/lotr-back pull request #4
Opened 2021-02-19 11:07 UTC by dgwiazda

liquibase without autostart

2021-02-19 11:22 UTC, adamK50 requested changes

2021-02-19 11:22 UTC, adamK50 commented on pom.xml
> +			<version>2.4.3</version>
Większośc tego co zaczyna się od spring-boot-starter to pakiet bibliotek bazujący na spring-boot-starter-parent i z niego bierze wersję. Dlatego w takich przypadakch nei dodajem version w dependency. Gdy będziemy podnosić wersję spring boota to podniesiemy tylko wersję parenta a nie każdego dependecy

2021-02-19 11:22 UTC, adamK50 commented on src/main/resources/mavenPostgreSQL/pom.xml
> +<project  xmlns="http://maven.apache.org/POM/4.0.0"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
To co tutaj stworzyłeś to drugi pom, którego nie potrzebujemy. Mamy pom główny, w którym mogą znajdować się różne pluginy, ale nie jestem przekonany czy plugin będzie nam potrzebny.
Pierwszym krokiem jest aplikacja, która uruchomi liquibase bez żadnych pluginów.
Usuń zatem proszę tego poma i wyczyść ręcznie schemat bazy danych. Uruchom aplikację i zobacz czy wtedy nowa tabelka powstanie - prawdopodobnie nie ze względu na złą ścięzkę, w której trzymane są pliki dbcghangelog.xml - domyslnie powinno leżeć prawdpodobnie w src/main/resource ale to do sprawdzenia

2021-02-19 11:22 UTC, adamK50 commented on src/main/resources/mavenPostgreSQL/liquibase.properties
> +password: mysecretpassword
Na każdym środowisku adres do bazy danych może być inny - tak samo jak hasło i nazwa użytkownika. Te wartości nalezy sprametryzować poprzez zmienne środowiskowe, które każdy developer ustawi sobie potem sam.
podpowiedź: robi się to przez ${NAZWA_ZMIENNEJ}. gdzie NAZWA_ZMIENNEJ ustawia się potem no w intelliJ jesli uruchamiasz aplikację z IDE

2021-02-19 13:02 UTC, adamK50 requested changes

2021-02-19 13:02 UTC, adamK50 commented on src/main/resources/application.properties
> +spring.liquibase.change-log=classpath:/mavenPostgreSQL/dbchangelog.xml
jak przeniesiesz dbchangelog.xml z mavenPostgreSQL do resource to ta linijka będzie do wywalenia

2021-02-19 13:02 UTC, adamK50 commented on src/main/resources/application.properties
> +spring.datasource.username=${database_username}
te zmienne środowiskowe powinny być ustawiane inaczej: pogoogla environemnt variables spring application yaml

2021-02-19 13:02 UTC, adamK50 commented on pom.xml
> +		</dependency>
to się tak czepiam tylko ale dla jasności róbmy tak, że wszystkie dependency ze springa na górze, wszystkie inne na dole

2021-02-19 13:40 UTC, dgwiazda commented on src/main/resources/application.properties
> +spring.datasource.username=${database_username}
a gdzie każdy użytkownik ma przechowywać te dane? W zmiennych środowiskowych windowsa na przykład?

2021-02-19 13:44 UTC, adamK50 commented on src/main/resources/application.properties
> +spring.datasource.username=${database_username}
Zmienne środowiskowe można podać w intelliJ tez. Configuration -> Edit Configuration -> Environment Variables: tam je definiujesz

2021-02-22 09:34 UTC, adamK50 requested changes
Już jest prawie git - została tylko kosmetyka :)

2021-02-22 09:34 UTC, adamK50 commented on src/main/resources/application.properties
> +spring.datasource.password=${db_password}
Moja wina, nie wspomniałem o tym wcześniej. Konwencja dla zmiennych środowiskowych jest taka, że są z wielkich liter. Druga sprawa jest taka, że cały url jest pod jedną zmienną środowiskową.

2021-02-22 09:34 UTC, adamK50 commented on src/main/resources/dbchangelog.xml
> +    <changeSet  id="1"  author="dgwiazda">
Ta tabelka jest na razie taką wstępną, potem sobie to zmienimy, ale jeśli chodzi o id to może przyjmimy sobie taką konwencję: 
<unix_timestamp>_<jakas_znaczaca_nazwa_tego_co_jest_w_changesecie>

2021-02-22 11:58 UTC, adamK50 requested changes
Prawie git :)

2021-02-22 11:58 UTC, adamK50 commented on src/main/resources/dbchangelog.xml
> +    <property name="now" value="UNIX_TIMESTAMP()" dbms="postgresql"/>
Z takim czymś będziemy mieli problem, bo liquibase działa tak:

    Tworzy sobie tabelkę i dodaje tam wpisy o wszystkich wgranych skryptach.
    Na podstawie zawartości skryptu do wgrania tworzy sobie checksumę.
    Sprawdza czy dla klucza id, author już istnieje jakiś wpis
    3a Jeśli nie to wgrywa nowy skrypt
    3b Jesli tak to porównuje z poprzednią cheksumą: Jesli taka sama to przechodzi do kolejnego skryptu. Jesli nie to zgłasza błąd

Przy takiej konfiguracji jaką zrobiłeś przy każdym uruchamianiu liquibase będzie nowa wartość dla id,author bo id zmienia się przy każdym wywołaniu. Dlatego id musi być z góry ustalone.
To co trzeba zrobić to przy dodawaniu skryptu sprawdzić sobie unix timestamp i dodać go ręcznie.
Unix timestamp dlatego, że jest bardzo małe prawdopodobieństwo, że ktoś akurat w tym samym czasie go sobie sprawdzi, a timestamp daje też nam jakąś chronologię.

2021-02-24 19:38 UTC, dgwiazda commented
Szef niby naprawione tutaj, ale no na nowym branchu feature-swagger jest sobie commit stąd, ale jakbyś se go spullował to program nie działa bo do jego działania potrzebne są te application.properties. I to ma tak zostać bo tu jest branch do liquibase a tam do swaggera i elo?

2021-02-25 08:23 UTC, adamK50 commented
> Szef niby naprawione tutaj, ale no na nowym branchu feature-swagger jest sobie commit stąd, ale jakbyś se go spullował to program nie działa bo do jego działania potrzebne są te application.properties. I to ma tak zostać bo tu jest branch do liquibase a tam do swaggera i elo?

W jednym i drugim branchu po prostu musi być ten plik. Każdy branch musi działać. Potem jak się robi merge to git sobie z tym poradzi i scali dwa pliki albo poprosi Cię o zrobienie tego ręcznie. W każdym razie - ten branch jest git! - merguje do developa

2021-02-25 08:23 UTC, adamK50 approved these changes
Teraz gituwa

2021-02-25 08:24 UTC, merged