Feature swagger
adamK50/lotr-back pull request #5
Opened 2021-02-25 10:30 UTC by dgwiazda

dałem tu wszystkie commity z feature-reading i ten pierwszy ze swaggera se został. Ogólnie robiłem to w ten sposób, że w reading zrobiłem git log, pokopiowałem wszystkie nazwy commitów i zrobiłem z nich cherry-picka. Po kolei się wrzucały te commity i wstawiały błędy w kod co bym sobie je przejrzał chyba, no i po git cherry-pick --continue wyskakiwał mi tekst z pliku EDITcośtam i mówił co updatuje tym commitem i ni chu chu nie wiem jak się po tym obchodzić, bo ani wyjść ani coś zrobić i za każdym razem jakoś fartem wychodziłem. Kojarzę że jakieś :qa! się wpisuje ale czasem działa czasem not lolz.

2021-02-25 11:26 UTC, adamK50 commented
> dałem tu wszystkie commity z feature-reading i ten pierwszy ze swaggera se został. Ogólnie robiłem to w ten sposób, że w reading zrobiłem git log, pokopiowałem wszystkie nazwy commitów i zrobiłem z nich cherry-picka. Po kolei się wrzucały te commity i wstawiały błędy w kod co bym sobie je przejrzał chyba, no i po git cherry-pick --continue wyskakiwał mi tekst z pliku EDITcośtam i mówił co updatuje tym commitem i ni chu chu nie wiem jak się po tym obchodzić, bo ani wyjść ani coś zrobić i za każdym razem jakoś fartem wychodziłem. Kojarzę że jakieś :qa! się wpisuje ale czasem działa czasem not lolz.

Wydarzyło się teraz coś takiego:
1. Od develop odbiłeś brancha feature-creature
2. Skomitowałes sobie parę razy na feature-creature
3. Od develop odbiłeś brancha feature-swagger
4. Skomitowałeś sobie coś na feature-swagger
5. Pull request z feature-creature do developa został zmergowany, co spowodowało, że na develope powstal jeden dodatkowy commit (bo merge był poprzez squash commit zrobiony) i chcesz teraz zrobić pull requesta z feature-swagger do develop. Czyli branch origin/develop jest o jeden komit do przodu względem brancha develop z którego odbiłeś feature-swagger.
Co musisz zrobić?
1. Cofnać to co zrobiłeś z tymi cherry pickami. Stan będzie taki, że na feature-swagger będziesz miał tylko swoje zmiany dotyczące swaggera (nie wiem czy to był jeden commit czy dwa)
2. Zrobić merge z brancha develop do Twojego brancha feature-swagger.
3. Wystawić pull requesta z feature-swagger do develop

2021-02-25 12:20 UTC, dgwiazda commented
no prawda, prościej tak, ale to przyniesie ten sam skutek tyle, że w jednym commicie nie?

2021-02-25 12:53 UTC, adamK50 requested changes
Dodaj jakiś testowy kontroller do aplikacji i zobacz czy działa swagger.

2021-02-25 12:53 UTC, adamK50 commented on pom.xml
> +			<version>2.9.2</version>
jest już wersja 3 swaggera

2021-02-25 12:53 UTC, adamK50 commented on pom.xml
> +		<dependency>
po co ta biblioteka?

2021-02-25 12:53 UTC, adamK50 commented on src/main/java/com/smusik/games/lotrback/LotrBackApplication.java
> +import springfox.documentation.swagger2.annotations.EnableSwagger2;
dodałeś EnableSwagger ale brakuje @EnableSwagger zdaje się na klasie

2021-02-25 13:36 UTC, adamK50 requested changes
W tym feature tylko swagger i miał być jakiś testowy controller, który zwróci cokolwiek żeby potwierdzić, że swagger działa. Także znowu zabawa z komitami hehe, żeby przenieść częśc z tego brancha na inny

2021-02-26 08:32 UTC, adamK50 requested changes
Pisałeś o tym targecie, a target to pliki wynikowe z builda mavenowego, więc ich nie chcemy.
Po to każdy ma mavena, żeby sobie samemu zbudować projekt.
Sam kod to często kilkaset KB a z targetem robi się już kilkadziesiąt MB, więc bez sensu to ściągać.
Żeby target Ci nie wchodził w commity to trzeba dodać do gitignora target*
Popraw więc to proszę i będziem mergować

2021-02-26 09:35 UTC, dgwiazda commented
Jak wszystko bangla to mam teraz do bazy wrzucić te excele i porobić jakieś testy?

2021-02-26 09:41 UTC, adamK50 approved these changes
Gitara, merguje

2021-02-26 09:42 UTC, merged