Feature creatures tables
adamK50/lotr-back pull request #8
Opened 2021-03-02 11:15 UTC by dgwiazda

Nie wiem czy pozwalasz na zrobienie tego w jednym branchu, ale chciałem w kolejnym branchu zrobić tą główną tabele Creature z połączeniami do tabel z tego brancha(creatures-tables) i w jeszcze kolejnym zrobić te tabele do połączeń ManyToMany

2021-03-02 20:52 UTC, dgwiazda commented
i ogólnie nie bardzo wiem jak logback zniknął z resources brancha develop

2021-03-08 14:47 UTC, adamK50 requested changes
Te zmiany co są w jednym entity trzeba zrobić wszedzie. 
W dalszym ciągu coś jest nie tak z gitignore

2021-03-08 14:47 UTC, adamK50 commented on target/classes/application.properties
> +spring.datasource.url=${DB_URL}
Na pewno dorzuciłeś do gitignore target* ? Bo coś nie podłapało. Może nie target* trzeba dodać tylko coś podobnego?

2021-03-08 14:47 UTC, adamK50 commented on src/main/resources/dbchangelog.xml
> +            option varchar(100) not null
formatowanie się rozjechalo - tu powinny być dodatkowe taby

2021-03-08 14:47 UTC, adamK50 commented on src/main/java/com/smusik/games/lotrback/persistence/model/FractionEntity.java
> +public class FractionEntity {
@Table - takie coś pozwoli nam na używanie innych nazw w modelu i innych w aplikacji. Generalnie bardzo często stosuje się wzór nazw w bazie taki: T_(że tabla) _COS_TAM_COS_TAM
czyli w naszym przypadku byłoby to T_FRACTION.
W kodzie mielibyśmy 
@Table(name = "T_FRACTION)
FractionEntity

2021-03-08 14:47 UTC, adamK50 commented on src/main/java/com/smusik/games/lotrback/persistence/model/FractionEntity.java
> +    @Id
Dałeś w bazie jako id typ serial - to jest taki byt postgresowy, który od razu tworzy sekwencje i z niej korzysta przy dodawaniu nowego wpisu. Fajna sprawa, ale działa trochę automagicznie. Nauczymy się zatem robić to świadomie. Dodaj sekwencje bazodanowe dla tabel, do których będziemy coś zapisywać. Ich identyfikatory zrób jako biginteger albo inny typ bazodawnoy przetrzymujący duże liczby. W javie skorzystaj z @SequenceGenerator (to jest albo z javax.persistance albo z hibernate)
Ustaw allocationSize w tych generatorach na 1

2021-03-08 14:47 UTC, adamK50 commented on src/main/java/com/smusik/games/lotrback/persistence/model/FractionEntity.java
> +}
No i teraz chłopie zagadka jak na rozmowie kwalifikacyjnej. 
Equals, HashCode, ToString - co to za metodki? Dlaczego ich tu nie ma? Dlaczego nie powinno ich tu być? Co to w ogóle daje? Jakie są kontrakty tych metod?

2021-03-08 14:47 UTC, adamK50 commented on src/main/java/com/smusik/games/lotrback/persistence/model/FractionEntity.java
> +    private Integer id;
raczej regułą jest, że jednak id robimy jako Long - nawet jesli spodziewamy się niewielkiej ilości danych. Dla innych kolumn już co innego - robimy często integery albo inne typy.

2021-03-08 14:47 UTC, adamK50 commented on src/main/java/com/smusik/games/lotrback/persistence/model/MagicEntity.java
> +public class MagicEntity {
to samo co w klasie FractionEntity

2021-03-08 14:47 UTC, adamK50 commented on src/main/java/com/smusik/games/lotrback/persistence/model/OptionEntity.java
> +    String option;
brak modyfikatorów dostępu private

2021-03-09 15:58 UTC, dgwiazda commented on src/main/java/com/smusik/games/lotrback/persistence/model/FractionEntity.java
> +}
no to tak:
Equals - metoda do porównywania dwóch obiektów
Hashcode - również metoda do porównywania obiektów typu Hash, na końcu metody i tak wywoływana jest metoda equals
toString - no to przekształca jakiś typ danych w typ String. Można w klasie overridować tę metodę, żeby na przykład pisząc System.out.println(taKlasa) wyszło coś co chcemy, by się wyświetlało, na przykład wszystkie atrybuty oraz ich wartości.
Nie ma ich tu bo nie było na razie potrzeby chyba ich używać.
Dlaczego nie powinno? To bym powiedział, że jakby przyszła potrzeba do porównywania między sobą obiektów klasy to byśmy dodali, a nie że nie powinno ich być.
Co to daje to chyba napisałem wyżej.
Kontrakty są takie, że jeśli 2 obiekty są takie same według Equals to **muszą** być takie same według HashCode, a jak takie same według HashCode to **nie muszą** według Equals.
No i jakieś zależności w Equals chyba też się nazywa kontraktami, np, że: jak x.equals(y) to y.equals(x), jak x.equals(y) i y.equals(z) to z.equals(x) i nie wiem co jeszcze.
To to było z głowy. Jak mam się wyszkolić to powiedz, a jak jakoś własnymi słowami wyjaśniasz to go

2021-03-09 16:25 UTC, dgwiazda commented on target/classes/application.properties
> +spring.datasource.url=${DB_URL}
nie wiem czy te zmiany w gitignore powinno być widać instant? Bo próbuję sposobów, robię run, klikam commit a ten target/changelog tam nadal się wrzuca. Także albo nadal samfink is not jes albo to może być widoczne w commicie a później się jakoś konfiguruje? Powinno być tak, że się targety znajdują w tych "Unversioned files" czy jakoś tak czy wgl nie powinno być ich w okienku commitowym?

2021-03-10 13:57 UTC, adamK50 requested changes
Wydaje mi się, że żeby usnąć te targety to musisz zrobić reset soft na całym branchu, potem commit i force push.

2021-03-10 13:57 UTC, adamK50 commented on src/main/resources/dbchangelog.xml
> +            create table option
nazwa tabeli musi być taka sama jak w @Table dla entity
czyli zamiast option, mamy t_option

2021-03-10 13:57 UTC, adamK50 commented on src/main/resources/dbchangelog.xml
> +            create table special_attack
To samo tu z nazwą

2021-03-10 21:26 UTC, adamK50 approved these changes

2021-03-10 21:35 UTC, merged