Feature creatures tables
adamK50/lotr-back pull request #9
Opened 2021-03-12 11:47 UTC by dgwiazda

2021-03-12 11:48 UTC, dgwiazda commented
czekaj adasiu nic nie rób bo znowu odwaliłem

2021-03-15 20:53 UTC, adamK50 requested changes
Ja to po tych drobnych poprawakch zmerguje, ale odnoszę wrażenie, że lepsze byłyby jednak tabele. Dane będziemy wciągać pewnie w dużej mierze z exceli do bazy, a nie da się w runtime stowrzyć enuma. No ale nic - najwyżej będziemy zmieniać

2021-03-15 20:53 UTC, adamK50 commented on src/main/java/com/smusik/games/lotrback/persistence/model/FractionEntity.java
>      private String fraction;
Na wszystkich class member muszą być adnotacje @Column zdaje się, bo inaczej się nie zmapuje.

Można też @Coulmn stawiać przy geterach do danych pól, ale trzeba zachować jedną konwencję: albo na polach albo na getach

2021-03-18 19:43 UTC, adamK50 approved these changes

2021-03-18 19:44 UTC, merged